function gAtts = getOoiGliderFlatNcAttributes()

gAtts = struct('Metadata_Conventions', 'Unidata Dataset Discovery v1.0',...
    'acknowledgment', 'This deployment supported the National Science Foundation and the Consortium for Ocean Leadership',...
    'comment', 'Data is not to be used for scientific purposes.',...
    'contributor_name', 'John Kerfoot',...
    'contributor_role', 'Data Manager',...
    'creator_email', 'kerfoot@marine.rutgers.edu',...
    'creator_name', 'John Kerfoot',...
    'creator_url', 'http://marine.rutgers.edu/cool/auvs',...
    'date_created', '',...
    'date_issued', '',...
    'date_modified', '',...
    'format_version', 'Glider_NetCDF_Profile_v1.0',...
    'history', '',...
    'id', '',...
    'institution', 'OOI',...
    'keywords', 'AUVS > Autonomous Underwater Vehicles, Oceans > Ocean Pressure > Water Pressure, Oceans > Ocean Temperature > Water Temperature, Oceans > Salinity/Density > Conductivity, Oceans > Salinity/Density > Density, Oceans > Salinity/Density > Salinity',...
    'keywords_vocabulary', 'GCMD Science Keywords',...
    'license', 'These data were collected by the Ocean Observatory Initiative (OOI) project purely for internal system development purposes during the construction phase of the project and are offered for release to the public with no assurance of data quality, consistency, temporal continuity or additional support. The OOI Program assumes no liability resulting from the use of these data for other than the intended purpose. No data quality assurance steps have been implemented on this data to date.',...
    'metadata_link', '',...
    'naming_authority', 'edu.rutgers.marine',...
    'platform_type', 'Slocum',...
    'processing_level', 'profile',...
    'project', 'Ocean Observatories Initiative',...
    'publisher_email', 'kerfoot@marine.rutgers.edu',...
    'publisher_name', 'John Kerfoot',...
    'publisher_url', 'http://rucool.marine.rutgers.edu',...
    'references', 'http://oceanobservatories.org',...
    'sea_name', '',...
    'source', 'Observational data from a profiling glider',...
    'standard_name_vocabulary', 'CF-1.6',...
    'summary', 'Observational data from an OOI Global Station Papa profiling glider',...
    'title', 'OOI CGSN Glider Dataset');